eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka

server:
  port: 8182
spring:
  application:
    name: students
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: student
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
